/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchHealthCheck200Response {
    /// HealthCheck status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl FetchHealthCheck200Response {
    pub fn new() -> FetchHealthCheck200Response {
        FetchHealthCheck200Response {
            status: None,
        }
    }
}


