/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentsEnumStatus {
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "cancel")]
    Cancel,

}

impl ToString for PaymentsEnumStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Complete => String::from("complete"),
            Self::Cancel => String::from("cancel"),
        }
    }
}

impl Default for PaymentsEnumStatus {
    fn default() -> PaymentsEnumStatus {
        Self::Complete
    }
}




