/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentsEnumBankAccountType {
    #[serde(rename = "consumer-checking")]
    ConsumerChecking,
    #[serde(rename = "consumer-savings")]
    ConsumerSavings,
    #[serde(rename = "commercial-checking")]
    CommercialChecking,

}

impl ToString for PaymentsEnumBankAccountType {
    fn to_string(&self) -> String {
        match self {
            Self::ConsumerChecking => String::from("consumer-checking"),
            Self::ConsumerSavings => String::from("consumer-savings"),
            Self::CommercialChecking => String::from("commercial-checking"),
        }
    }
}

impl Default for PaymentsEnumBankAccountType {
    fn default() -> PaymentsEnumBankAccountType {
        Self::ConsumerChecking
    }
}




